# Generated by Django 4.2.29 on 2026-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='average_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='club',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
