# Generated by Django 4.2.29 on 2026-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_email_confirmed_alter_club_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
