# Generated by Django 4.2.29 on 2026-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_court_rating_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
